% Return surface values from a large control volume

function[LV_mass_snapshot, ...
         LV_mass_flux, LV_facesize] = coarse_grain_CV_mass(LV_botx, LV_topx, ...
                                                           LV_boty, LV_topy, ...
                                                           LV_botz, LV_topz,m,resultfile_dir)

    %Read Header file
    read_header

    %Read CV field
    [mass_flux,mass_snapshot]=read_mflux('./mflux','./msnap',resultfile_dir,m);

    %==============Get size of CV face==============
    LV_facesize(1) = (LV_topx-LV_botx+1)*binsize(1);
    LV_facesize(2) = (LV_topy-LV_boty+1)*binsize(2);
    LV_facesize(3) = (LV_topz-LV_botz+1)*binsize(3);

    %==============Mass snapshot=================
    LV_mass_snapshot        = squeeze(sum(sum(sum( ...
                                    mass_snapshot(LV_botx:LV_topx, ...
                                                  LV_boty:LV_topy, ...
                                                  LV_botz:LV_topz,:) ...
                                       ,1),2),3));

    %============== surface flux==============
    % X Surfaces
    LV_mass_flux(1) =  sum(sum(sum(mass_flux(   LV_botx, ...
                                                LV_boty:LV_topy, ...
                                                LV_botz:LV_topz,1) ...
                                ,1),2),3);
    LV_mass_flux(4) = sum(sum(sum(mass_flux(	LV_topx, ...
                                                LV_boty:LV_topy, ...
                                                LV_botz:LV_topz,4) ...
                                ,1),2),3);
    % Y Surfaces
    LV_mass_flux(2) = sum(sum(sum(mass_flux(LV_botx:LV_topx, ...
                                            	LV_boty, ...
                                            LV_botz:LV_topz,2) ...
                             ,1),2),3);
    LV_mass_flux(5) = sum(sum(sum(mass_flux(LV_botx:LV_topx, ...
                                            	LV_topy, ...
                                            LV_botz:LV_topz,5) ...
                             ,1),2),3);
    % Z Surfaces
    LV_mass_flux(3) = sum(sum(sum(mass_flux(LV_botx:LV_topx, ...
                                            LV_boty:LV_topy, ...
                                            	LV_botz,3) ...
                             ,1),2),3);
    LV_mass_flux(6) = sum(sum(sum(mass_flux(LV_botx:LV_topx, ...
                                            LV_boty:LV_topy, ...
                                            	LV_topz,6) ...
                             ,1),2),3);

end
