#!/bin/sh
#
# Displays the difference between a chosen input folder (generated by the
# pack_case command) and the current input files
#

if [ $# -lt 1 ]; then
	echo "Input of the form diff_case.sh [Case Name]"
else
	diff ./$1/input.file  ./../CFD_dCSE/src_code/grid_generation/
	diff ./$1/input.setup ./../CFD_dCSE/src_code/setup/
	diff ./$1/uy_input ./../CFD_dCSE/src_code/setup/
	diff ./$1/param.inc  ./../CFD_dCSE/src_code/main_code/
	diff ./$1/input  ./../CFD_dCSE/src_code/main_code/
	diff ./$1/COUPLER.in  ./../coupler_dCSE/src_code/
	diff ./$1/MD.in  ./../coupler_dCSE/src_code/md_data/
fi
