%Subroutine to read report generated by DNS code
% Usage:
%
% read_report(filename)
%

function[xpg, ypg, zpg, Lx, Ly, Lz, dx, dy, dz]=read_report(filename)

% Check file exists
fid = fopen(filename);
switch fid
    case -1
        error(['Specified grid file ''',filename,''' not found in current directory'])
end
fclose(fid);

% == Read Report file ==

%Get xpg
fileout=textread(filename,'%s');
index=find(not(cellfun('isempty', strfind(fileout,'nx'))));
xpg = str2double(fileout{index+1});
%Get ypg
fileout=textread(filename,'%s');
index=find(not(cellfun('isempty', strfind(fileout,'ny'))));
ypg = str2double(fileout{index+1});
%Get zpg
fileout=textread(filename,'%s');
index=find(not(cellfun('isempty', strfind(fileout,'nz'))));
zpg = str2double(fileout{index+1});

%Get Lx
fileout=textread(filename,'%s');
index=find(not(cellfun('isempty', strfind(fileout,'xL'))));
Lx = str2double(fileout{index+1});
%Get Ly
fileout=textread(filename,'%s');
index=find(not(cellfun('isempty', strfind(fileout,'yL'))));
Ly = str2double(fileout{index+1});
%Get Lz
fileout=textread(filename,'%s');
index=find(not(cellfun('isempty', strfind(fileout,'zL'))));
Lz = str2double(fileout{index+1});

%Get dx
fileout=textread(filename,'%s');
if (max(not(cellfun('isempty', strfind(fileout,'dx')))) == 0)
    dx = Lx/(xpg-3);
else
    index=find(not(cellfun('isempty', strfind(fileout,'dx'))));
    dx = str2double(fileout{index+2});
end

%Get dy
fileout=textread(filename,'%s');
if (max(not(cellfun('isempty', strfind(fileout,'dy')))) == 0)
    dy = Ly/(ypg-3);
else
    index=find(not(cellfun('isempty', strfind(fileout,'dy'))));
    dy = str2double(fileout{index(1)+2});
    maxdy = str2double(fileout{index(2)+2});
    if (abs(maxdy-dy) > 0.0000)
        disp('Grid stretching used - dy value returned is maximum y cellsize')
        dy = maxdy;
    end
end
%Get dz
fileout=textread(filename,'%s');
if (max(not(cellfun('isempty', strfind(fileout,'dz')))) == 0)
    dz = Lz/(zpg-3);
else
    index=find(not(cellfun('isempty', strfind(fileout,'dz'))));
    dz = str2double(fileout{index+2});
end

end