% Return surface values from a large control volume

function[LV_mass_snapshot, ...
         LV_mass_flux, LV_facesize] = coarse_grain_CV_mass(LV_botx, LV_topx, ...
                                                           LV_boty, LV_topy, ...
                                                           LV_botz, LV_topz,m,resultfile_dir)

    %Read Header file
    read_header

    %Read CV field
    [mass_flux,mass_snapshot]=read_mflux('./mflux','./msnap',resultfile_dir,m);

    %==============Get size of CV face==============
    LV_facesize(1) = (LV_topx-LV_botx+1)*binsize(1);
    LV_facesize(2) = (LV_topy-LV_boty+1)*binsize(2);
    LV_facesize(3) = (LV_topz-LV_botz+1)*binsize(3);

    %==============Mass snapshot=================
    LV_mass_snapshot        = squeeze(sum(sum(sum( ...
                                    mass_snapshot(LV_botx:LV_topx, ...
                                                  LV_boty:LV_topy, ...
                                                  LV_botz:LV_topz,:) ...
                                       ,1),2),3));

    %============== surface flux==============
%     LV_mass_flux = zeros(6,1);
%     for p = LV_botx:LV_topx
%     for q = LV_boty:LV_topy
%     for r = LV_botz:LV_topz
%         LV_mass_flux(:) = LV_mass_flux(:) + squeeze(mass_flux(p,q,r,:));
%     end
%     end
%     end
% 
%     LV_mass_flux = zeros(6,1);
%     LV_mass_flux(1) =  sum(sum(sum(mass_flux(   LV_botx, ...
%                                                 LV_boty:LV_topy, ...
%                                                 LV_botz:LV_topz,1) ...
%                          ,1),2),3);
%     LV_mass_flux(4) = sum(sum(sum(mass_flux(	LV_topx, ...
%                                                 LV_boty:LV_topy, ...
%                                                 LV_botz:LV_topz,4) ...
%                                  ,1),2),3);
%     %Molecules can cross more than one surface -- check when this happen
%     for p = LV_botx+1:LV_topx-1
%     for q = LV_boty+1:LV_topy-1
%     for r = LV_botz+1:LV_topz-1
%         if (squeeze(mass_flux(p,q,r,1))==squeeze(mass_flux(p-1,q-1,r-1,4)))
%             
%         end
%         LV_mass_flux(1) = LV_mass_flux(1) + squeeze(mass_flux(p,q,r,1))+squeeze(mass_flux(p-1,q-1,r-1,4))
%         LV_mass_flux(4) = LV_mass_flux(4) + squeeze(mass_flux(p,q,r,4))+squeeze(mass_flux(p+1,q+1,r+1,1))
%     end
%     end
%     end



    LV_mass_flux(1) =  sum(sum(sum(mass_flux(   LV_botx, ...
                                                LV_boty:LV_topy, ...
                                                LV_botz:LV_topz,1) ...
                                ,1),2),3);
    LV_mass_flux(4) = sum(sum(sum(mass_flux(	LV_topx, ...
                                                LV_boty:LV_topy, ...
                                                LV_botz:LV_topz,4) ...
                                ,1),2),3);
    % Y Surfaces
    LV_mass_flux(2) = sum(sum(sum(mass_flux(LV_botx:LV_topx, ...
                                            	LV_boty, ...
                                            LV_botz:LV_topz,2) ...
                             ,1),2),3);
    LV_mass_flux(5) = sum(sum(sum(mass_flux(LV_botx:LV_topx, ...
                                            	LV_topy, ...
                                            LV_botz:LV_topz,5) ...
                             ,1),2),3);
    % Z Surfaces
    LV_mass_flux(3) = sum(sum(sum(mass_flux(LV_botx:LV_topx, ...
                                            LV_boty:LV_topy, ...
                                            	LV_botz,3) ...
                             ,1),2),3);
    LV_mass_flux(6) = sum(sum(sum(mass_flux(LV_botx:LV_topx, ...
                                            LV_boty:LV_topy, ...
                                            	LV_topz,6) ...
                             ,1),2),3);

end
